var ie=document.all?true:false,textbox,resultbox,cl,lang,user,uid,currenttitle,tab1,language,plugin_urls,loaded_plugins,unrendered,css_urls,currentWidth,haveindex=false;
function loading(){plugin_urls=[];loaded_plugins=[];css_urls=[];lang="";tab1=tabs();tab1.create({name:"tabs",target:"tabdiv",width:"100%",height:"100%",info:[{label:"Contents",content:"ctab1",foc:""},{label:"Index",content:"ctab2",foc:""},{label:"Search",content:"ctab3",foc:"keyword"},{label:"Help",content:"ctab4",foc:""}]});tab1.tabs[0].onclick=tabchange;tab1.tabs[1].onclick=tabchange;if(readCookie("lang"))lang=readCookie("lang");languages();cl="tree"}
var updateLayout=function(){if(window.innerWidth!=currentWidth){currentWidth=window.innerWidth;document.body.setAttribute("orient",currentWidth==320?"profile":"landscape");window.scrollTo(0,1)}};function tabchange(){tab1.selected==0&&tree.updateNode(tree.activenode);tab1.selected==1&&!haveindex&&getindex()}
function printpage(){var b=document.getElementById("help").innerHTML;win=window.open("","mywindow","width=500,height=500");self.focus();win.document.open();win.document.write("<html><head><title>Help Page</title>");win.document.write("<link rel='stylesheet' type='text/css' href='theme/default/css/ui.css'><link></head>");win.document.write(b+"</body></html>");win.document.close();win.print();win.close()}function dummy(){}
function getindex(){ajax("handlers/getindex.php?lang="+lang,null,function(b){b=b.responseXML.documentElement.getElementsByTagName("tag");for(var a=document.getElementById("indexpane"),c="",d=0;d<b.length;d++){var e=b[d],f=e.getAttribute("label");c+="<div id='tag-"+f.replace(" ","_")+"' class='indextag'>"+f+"</div>";e=e.getElementsByTagName("node");for(var g=0;g<e.length;g++){var h=e[g],k=h.getAttribute("label");h=h.getAttribute("id");c+="<div style='margin-left:20px;'><a href='javascript:indexpage("+
h+',"'+f+"\")'>"+k+"</a></div>"}}a.innerHTML=c;haveindex=true},"GET")}function indexpage(b){ajax("handlers/getpage.php?id="+b+"&lang="+lang,null,function(a){a=a.responseText;a=Wiky.toHtml(a);document.getElementById("help").innerHTML=a;RedirectLocation("LocationAnchor",b,"#"+b)},"GET");tree.updateNode(b);cl="index"}
function changelanguage(){var b=document.getElementById("langsel");lang=b.options[b.selectedIndex].value;if(lang!=""){b=new Date;b.setTime(b.getTime()+2592E6);document.cookie="lang="+lang+"; expires="+b.toGMTString();ajax("language/"+lang+".json",null,function(a){a=eval("("+a.responseText+")");tab1.setLabel(0,a.tabs.contents);tab1.setLabel(1,a.tabs.index);tab1.setLabel(2,a.tabs.search);document.getElementById("searchtype").innerHTML=a.tabs.type;document.getElementById("searchlist").value=a.tabs.list;
language=a;tree.getTree("handlers/gettree.php?lang="+lang,"tree");haveindex=false;tab1.selected==1&&getindex();document.getElementById("keyword").value="";document.getElementById("searchresult").innerHTML=""});return false}}
function languages(){ajax("language/languages.json",null,function(b){b=eval("("+b.responseText+")");for(var a="",c=0;c<b.languages.length;c++)a+="<option value='"+b.languages[c].symbol+"'>"+b.languages[c].text+"</option>";document.getElementById("lang").innerHTML='<select id="langsel" onchange="changelanguage();">'+a+"</select>";a=document.getElementById("langsel");if(lang=="")lang=b.languages[0].symbol;a.value=lang;changelanguage()});return false}
function getRequestObject(){var b=null;try{this.postmode=true;b=new XMLHttpRequest}catch(a){try{this.postmode=false;b=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){b=new ActiveXObject("Microsoft.XMLHTTP")}}return b}
function search(){textbox=document.getElementById("keyword");resultbox=document.getElementById("searchresult");ajax("handlers/search.php?lang="+lang,"search="+encodeURIComponent(textbox.value),function(b){var a=b.responseXML.documentElement.getElementsByTagName("file"),c="";for(b=0;b<a.length;b++){var d=a[b];c+="<div class='list' onclick='searchClick(\""+d.getAttribute("name")+"\")'>"+d.getAttribute("title")+"</div>"}resultbox.innerHTML=c});return false}
function searchClick(b){ajax("handlers/getpage.php?id="+b+"&lang="+lang,null,function(a){a=a.responseText;a=Wiky.toHtml(a);for(var c=textbox.value.split(" "),d=0;d<c.length;d++){pattern="("+c[d]+")(?=[^>]*<)";a=a.replace(RegExp(pattern,"gi"),"<span style='background:#ffff00;display:inline-block;'>$1</span>")}document.getElementById("help").innerHTML=a;RedirectLocation("LocationAnchor",b,"#"+b)});tree.updateNode(b);cl="search"}
function plugins(){unrendered=[];for(var b in Wiky.plugins){var a=Wiky.plugins[b];unrendered.push(a);var c="plugins/"+a[0]+"/"+a[0]+".js";loadPlugin(c,a);ArrayContains(loaded_plugins,c)&&renderplugin(a)}}function clone(b){var a=function(){};a.prototype=b;return new a}function renderplugin(b){try{var a=eval("("+b[0].replace("-","_")+")"),c=clone(a);c.init(b[1],b[2]);c.render();ArrayRemove(unrendered,b)}catch(d){}}
function updateplugins(b){loaded_plugins.push(b);for(b=unrendered.length-1;b>-1;b--){var a=unrendered[b];ArrayContains(loaded_plugins,"plugins/"+a[0]+"/"+a[0]+".js")&&renderplugin(a)}}
function loadPlugin(b){if(!ArrayContains(plugin_urls,b)){plugin_urls.push(b);var a=document.createElement("script");a.src=b;a.type="text/javascript";if(a.readyState)a.onreadystatechange=function(){if(a.readyState=="loaded"||a.readyState=="complete"){a.onreadystatechange=null;updateplugins(b)}};else a.onload=function(){updateplugins(b)};document.getElementsByTagName("head")[0].appendChild(a)}}var last="";
function CheckForHash(){if(document.location.hash){var b=document.location.hash;b=b.substring(1);if(last==b)return;parseInt(b)!=tree.activenode&&tree.activenode!=""&&tree.click(b);var a=b.split("-");if(a.length>1)if(a[1].substring(0,2)!=lang){b=document.getElementById("langsel");for(i=0;i<b.length;i++)if(b[i].value==a[1].substring(0,2)){b.selectedIndex=i;break}lang=a[1].substring(0,2);changelanguage();return}anchor(b);tab1.setTab(3);last=b}updateLayout()}
function RenameAnchor(b,a){document.getElementById(b).name=a}function RedirectLocation(b,a,c){var d=c.split("-"),e=a.toString().split("#");e=e.length>1?"#"+e[1]:"";RenameAnchor(b,a);document.location.hash=d[0]+"-"+lang+e;plugins();anchor(c)}function anchor(b){anum=b.substring(1);b=document.body;b.scrollTop=0;if(parseInt(anum)!=anum){var a=anum.split("%23");if(a.length>1){a=document.getElementsByName(a[1]);if(a.length>0)b.scrollTop=a[0].offsetTop+80}}}function forward(){history.go(1)}
function back(){history.go(-1)}function readCookie(b){b=b+"=";for(var a=document.cookie.split(";"),c=0;c<a.length;c++){for(var d=a[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(b)==0)return d.substring(b.length,d.length)}return null}function pageFromPath(b){ajax("handlers/pageFromPath.php","lang="+lang+"&path="+encodeURIComponent(b),function(a){a=a.responseText.replace(/^\s+|\s+$/g,"");if(a>0)tree.click(a);else a==-1&&edit(b)})}
function ajax(b,a,c,d){if(d==null)d="POST";var e=getRequestObject();e.onreadystatechange=function(){e.readyState==4&&c(e)};e.open(d,b,true);d=="POST"&&e.setRequestHeader("Content-type","application/x-www-form-urlencoded");e.send(a)}
function updatefldrfrm(b){var a=document.getElementById("fldrfrmname"),c=document.getElementById("fldrfrmaddpaste"),d=document.getElementById("fldrfrmcmt");if(b.id=="faddpage"){a.style.display="block";c.style.display="block";d.style.display="block"}if(b.id=="fremovefolder"){a.style.display="none";c.style.display="none";d.style.display="block"}if(b.id=="fcut"){a.style.display="none";c.style.display="none";d.style.display="none"}if(b.id=="fpaste"){a.style.display="none";c.style.display="block";d.style.display=
"block"}if(b.id=="frename"){a.style.display="block";c.style.display="none";d.style.display="block"}}function ArrayContains(b,a){for(var c=0;c<b.length;c++)if(b[c]==a)return true;return false}function ArrayRemove(b,a){for(var c=0;c<b.length;c++)b[c]==a&&b.splice(c,1)}var HashCheckInterval=setInterval("CheckForHash()",250);var tree={n:0,target:null,home:"",nodes:[],crumbs:[],activenode:"",activetitle:"",highlight:"#ccccff",normal:"#ffffff",updateNode:function(b){if(b&&this.nodes.length>0){b=parseInt(b);this.crumbs=[];this.expandnode(this.nodes[b]);this.crumbs.reverse();if(b in this.nodes){if(this.activenode!="")document.getElementById(this.nodes[this.activenode].id).style.backgroundColor=this.normal;this.activenode=b;this.activetitle=this.nodes[b].label;b=document.getElementById(this.nodes[b].id);b.style.backgroundColor=
this.highlight;var a=b.parentNode.parentNode,c=document.getElementById("toc");if(a.offsetTop-c.scrollTop+b.offsetHeight>c.offsetHeight)c.scrollTop=a.offsetTop+b.offsetHeight-c.offsetHeight;if(c.scrollTop>a.offsetTop)c.scrollTop=a.offsetTop}}},click:function(b){handler="handlers/getpage.php?id="+parseInt(b)+"&lang="+lang;ajax(handler,null,function(a){a=a.responseText;document.getElementById("help").innerHTML=Wiky.toHtml(a);RedirectLocation("LocationAnchor",b,"#"+b)},"GET");this.updateNode(b);cl="tree"},
getTree:function(b,a,c){this.nodes=[];this.home="";this.activenode=c==null?"":c;this.target=document.getElementById(a);var d=this;ajax(b,null,function(e){e=e.responseXML.documentElement;d.target.innerHTML="";tree.parseTree(e,d.target,0);if(document.location.hash)d.activenode==""&&!document.location.hash.substring(1)in d.nodes?tree.click(tree.home):tree.click(document.location.hash.substring(1));else tree.click(tree.home)},"GET",false)},parseTree:function(b,a,c){for(var d=0;d<b.childNodes.length;d++){var e=
b.childNodes[d];if(e.nodeName=="folder"){if(this.home=="")this.home=e.getAttribute("ref");this.n++;var f=document.createElement("div");f.className="node";var g="<div style='overflow:hidden;width:1000px;'><div class='toggle closed' id='toggle"+e.getAttribute("ref")+"' onclick='tree.togglenode("+e.getAttribute("ref")+")'></div><div id='treelabel"+e.getAttribute("ref")+"' class='closelabel' onclick='tree.click(\""+e.getAttribute("ref")+"\");' onselectstart='return false;' ondblclick='tree.togglenode("+
e.getAttribute("ref")+")'>"+e.getAttribute("label")+"</div></div>",h=document.createElement("div");h.id="treenode"+e.getAttribute("ref");f.innerHTML=g;f.appendChild(h);h.style.display="none";if(e.getAttribute("ref")!="")this.nodes[e.getAttribute("ref")]={ref:e.getAttribute("ref"),id:"treelabel"+e.getAttribute("ref"),label:e.getAttribute("label"),pid:a.id,owner:c};this.parseTree(e,h,e.getAttribute("ref"));a.appendChild(f)}if(e.nodeName=="leaf"){if(this.home=="")this.home=e.getAttribute("ref");this.n++;
f=document.createElement("div");f.innerHTML="<div style='overflow:hidden;width:1000px;'><div id='treelabel"+e.getAttribute("ref")+"' class='leaf' onclick='tree.click(\""+e.getAttribute("ref")+"\");' onselectstart='return false;'>"+e.getAttribute("label")+"</div></div>";f.getAttribute("ref");a.appendChild(f);if(e.getAttribute("ref")!="")this.nodes[e.getAttribute("ref")]={id:"treelabel"+e.getAttribute("ref"),label:e.getAttribute("label"),pid:a.id,owner:c}}}},togglenode:function(b){var a=document.getElementById("treenode"+
b),c=document.getElementById("treelabel"+b);b=document.getElementById("toggle"+b);if(a.style.display=="block"){a.style.display="none";c.className="closelabel";b.className="toggle closed"}else{a.style.display="block";c.className="nodelabel";b.className="toggle open"}},expandnode:function(b){if(b){this.crumbs.push(b);if(b.owner!=0){var a=document.getElementById(b.pid),c=b.pid.substring(8),d=document.getElementById("treelabel"+c);c=document.getElementById("toggle"+c);a.style.display="block";d.className=
"nodelabel";c.className="toggle open";this.expandnode(this.nodes[b.owner])}}}};var tabs=function(){return{info:null,target:null,name:null,height:null,width:null,tabs:[],selected:0,setLabel:function(b,a){this.tabs[b].innerHTML=a},setTab:function(b){for(var a=0;a<this.info.length;a++){var c=this.tabs[a],d=document.getElementById(this.info[a].content);if(b==a){c.className="tabon";d.style.display="block";this.info[a].foc!=""&&document.getElementById(this.info[a].foc).focus()}else{d.style.display="none";c.className="taboff"}}},create:function(b){this.target=document.getElementById(b.target);
this.info=b.info;this.name=b.name;this.height=b.height;this.width=b.width;this.target.style.height=this.height;for(b=0;b<this.info.length;b++){var a=document.createElement("div");a.setAttribute("id",this.name+"tab"+b);a.className="taboff";a.innerHTML=this.info[b].label;var c=this;a.onmouseup=function(){for(var e=0;e<c.info.length;e++){var f=c.tabs[e],g=document.getElementById(c.info[e].content);if(f==this){f.className="tabon";g.style.display="block";c.info[e].foc!=""&&document.getElementById(c.info[e].foc).focus();
c.selected=e}else{g.style.display="none";f.className="taboff"}}};a.style.height="22px";this.tabs[b]=a;this.target.appendChild(a);var d=document.getElementById(this.info[b].content);d.style.left=0;d.style.display="none";d.style.top=a.offsetHeight-1+"px"}this.tabs[0].className="tabon";document.getElementById(this.info[0].content).style.display="block"}}};var Wiky={version:0.95,blocks:null,plugins:null,rules:{all:["Wiky.rules.pre","Wiky.rules.nonwikiblocks","Wiky.rules.wikiblocks"],pre:[{rex:/(\r?\n)/g,tmplt:"\u00b6"}],post:[{rex:/(^\xB6)|(\xB6$)/g,tmplt:""},{rex:/@([0-9]+)@/g,tmplt:function(b,a){return Wiky.restore(a)}},{rex:/\xB6/g,tmplt:"\n"}],nonwikiblocks:[{rex:/\\([%])/g,tmplt:function(b,a){return Wiky.store(a)}},{rex:/\[%(.*?)%\]/g,tmplt:function(b,a){return Wiky.store("<pre>"+Wiky.apply(a,Wiky.rules.code)+"</pre>")+"[p:"}}],wikiblocks:["Wiky.rules.nonwikiinlines",
"Wiky.rules.escapes",{rex:/(?:^|\xB6)(={1,6})(.*?)[=]*(?=\xB6|$)/g,tmplt:function(b,a,c){b=a.length;return":p]\u00b6<h"+b+">"+c+"</h"+b+">\u00b6[p:"}},{rex:/(?:^|\xB6)[-]{4}(?:\xB6|$)/g,tmplt:"\u00b6<hr/>\u00b6"},{rex:/\\\\([ \xB6])/g,tmplt:"<br/>$1"},{rex:/`(?:\{(.*?)\})([^`]+)`/g,tmplt:function(b,a,c){return Wiky.store("<span"+Wiky.style(a)+">"+c+"</span>")}},{rex:/(^|\xB6)([*01aAiIg]*[\.*])[ ]/g,tmplt:function(b,a,c){b=c.replace(/([*])/g,"u").replace(/([\.])/,"");return":"+b+"]"+a+"["+b+":"}},
{rex:/(?:^|\xB6);[ ](.*?):[ ]/g,tmplt:"\u00b6:l][l:$1:d][d:"},{rex:/\[(?:\{([^}]*)\})?(?:\(([^)]*)\))?\"/g,tmplt:function(b,a,c){return":p]<blockquote"+Wiky.attr(c,"cite",0)+Wiky.attr(c,"title",1)+Wiky.style(a)+">[p:"}},{rex:/\"\]/g,tmplt:":p]</blockquote>[p:"},{rex:/\[(\{[^}]*\})?\|/g,tmplt:":t]$1[r:"},{rex:/\|\]/g,tmplt:":r][t:"},{rex:/\|\xB6[ ]?\|/g,tmplt:":r]\u00b6[r:"},{rex:/\|/g,tmplt:":c][c:"},{rex:/^(.*)$/g,tmplt:"[p:$1:p]"},{rex:/(([\xB6])([ \t\f\v\xB6]*?)){2,}/g,tmplt:":p]$1[p:"},{rex:/\[([01AIacdgilprtu]+)[:](.*?)[:]([01AIacdgilprtu]+)\]/g,
tmplt:function(b,a,c,d){return Wiky.sectionRule(a==undefined?"":a,"",Wiky.apply(c,Wiky.rules.wikiinlines),!d?"":d)}},{rex:/\[[01AIacdgilprtu]+[:]|[:][01AIacdgilprtu]+\]/g,tmplt:""},{rex:/<td>(?:([0-9]*)[>])?([ ]?)(.*?)([ ]?)<\/td>/g,tmplt:function(b,a,c,d,e){return"<td"+(a?' colspan="'+a+'"':"")+(c==" "?' style="text-align:'+(c==e?"center":"right")+';"':e==" "?' style="text-align:left;"':"")+">"+c+d+e+"</td>"}},{rex:/<(p|table|h[1-6])>(?:\xB6)?(?:\{(.*?)\})/g,tmplt:function(b,a,c){return Wiky.store("<"+
a+Wiky.style(c)+">")}},{rex:/<p>([ \t\f\v\xB6]*?)<\/p>/g,tmplt:"$1"},"Wiky.rules.shortcuts"],nonwikiinlines:[{rex:/%(?:\{([^}]*)\})?(?:\(([^)]*)\))?(.*?)%/g,tmplt:function(b,a,c,d){return Wiky.store("<code"+(c?' lang="x-'+Wiky.attr(c)+'"':"")+Wiky.style(a)+">"+Wiky.apply(d,c?Wiky.rules.lang[Wiky.attr(c)]:Wiky.rules.code)+"</code>")}},{rex:/%(.*?)%/g,tmplt:function(){return Wiky.store("<code>"+Wiky.apply($2,Wiky.rules.code)+"</code>")}}],wikiinlines:[{rex:/\*([^*]+)\*/g,tmplt:"<strong>$1</strong>"},
{rex:/\(\+(.+?)\+\)/g,tmplt:"<ins>$1</ins>"},{rex:/(((http(s?))\:\/\/)?[A-Za-z0-9\._\/~\-: ]+\.(?:png|jpg|jpeg|gif|bmp))/gi,tmplt:function(b,a){return Wiky.store('<img src="'+a+'" alt="'+a+'"/>')}},{rex:/_([^_]+)_/g,tmplt:"<em>$1</em>"},{rex:/\^([^^]+)\^/g,tmplt:"<sup>$1</sup>"},{rex:/~([^~]+)~/g,tmplt:"<sub>$1</sub>"},{rex:/\(-(.+?)-\)/g,tmplt:"<del>$1</del>"},{rex:/\?([^ \t\f\v\xB6]+)\((.+)\)\?/g,tmplt:'<abbr title="$2">$1</abbr>'},{rex:/\[(?:\{([^}]*)\})?[Ii]ma?ge?\:([^ ,\]]*)(?:[, ]([^\]]*))?\]/g,
tmplt:function(b,a,c,d){return Wiky.store("<img"+Wiky.style(a)+' src="'+c+'" alt="'+(d?d:c)+'" title="'+(d?d:c)+'"/>')}},{rex:/#\]/g,tmplt:"</div>"},{rex:/\[#\s*([^ ,]+)[, ]([^\]]*);/g,tmplt:function(b,a,c){return Wiky.plug(a,c)}},{rex:/\[(\/[a-zA-z0-9_\u00A1-\uFFFF\-\/]+)\]/g,tmplt:function(b,a){return Wiky.store("<a href=\"javascript:pageFromPath('"+a+"');\">"+Wiky.word(a)+"</a>")}},{rex:/\[(http(s?)\:\/\/[^ ,]+)[, ]([^\]]*)\]/g,tmplt:function(b,a,c,d){return Wiky.store("<a class='extlink' href=\""+
a+c+'">'+d+"</a>")}},{rex:/\[([^ ,]+)[, ]([^\]]*)\]/g,tmplt:function(b,a,c){return Wiky.store('<a href="'+a+'">'+c+"</a>")}},{rex:/((mailto\:|javascript\:|(news|file|(ht|f)tp(s?))\:\/\/)[A-Za-z0-9\.:_\/~%\-+&#?!=()@\x80-\xB5\xB7\xFF]+)/g,tmplt:'<a href="$1">$1</a>'}],escapes:[{rex:/\\([|*_~\^])/g,tmplt:function(b,a){return Wiky.store(a)}},{rex:/\\&/g,tmplt:"&amp;"},{rex:/\\>/g,tmplt:"&gt;"},{rex:/\\</g,tmplt:"&lt;"}],shortcuts:[{rex:/---/g,tmplt:"&#8212;"},{rex:/--/g,tmplt:"&#8211;"},{rex:/[\.]{3}/g,
tmplt:"&#8230;"},{rex:/<->/g,tmplt:"&#8596;"},{rex:/<-/g,tmplt:"&#8592;"},{rex:/->/g,tmplt:"&#8594;"}],code:[{rex:/&/g,tmplt:"&amp;"},{rex:/</g,tmplt:"&lt;"},{rex:/>/g,tmplt:"&gt;"}],lang:{}},toHtml:function(b){Wiky.blocks=[];Wiky.plugins=[];return Wiky.apply(Wiky.sanitize(Wiky.apply(b,Wiky.rules.all)),Wiky.rules.post)},apply:function(b,a){if(b&&a)for(var c in a)b=typeof a[c]=="string"?Wiky.apply(b,eval(a[c])):b.replace(a[c].rex,a[c].tmplt);return b},plug:function(b,a){var c=eval("("+a+")"),d=b+"_"+
Wiky.plugins.length;Wiky.plugins.push([b,d,c]);return"<div id='"+d+"'>"},sanitize:function(b){var a=document.createElement("div");a.innerHTML=b;b=a.getElementsByTagName("*");for(var c=b.length-1;c>-1;c--){var d=b.item(c),e=d.tagName.toLowerCase();if(e=="object"||e=="iframe"||e=="embed")d.parentNode.removeChild(d);else{if(d.style.position=="absolute"||d.style.position=="relative")d.style.position="static";e=d.attributes;for(var f=e.length-1;f>-1;f--){var g=e[f].name;g.indexOf("on")==0&&d.removeAttribute(g)}}}return a.innerHTML},
store:function(b,a){return a?"@"+(Wiky.blocks.push(b)-1)+"@":"@"+(Wiky.blocks.push(b.replace(/@([0-9]+)@/g,function(c,d){return Wiky.restore(d)}))-1)+"@"},restore:function(b){return Wiky.blocks[b]},attr:function(b,a,c){return(b=b&&b.split(",")[c||0])?a?" "+a+'="'+b+'"':b:""},hasAttr:function(b,a){return RegExp(a+"=").test(b)},attrVal:function(b,a){return b.replace(RegExp("^.*?"+a+'="(.*?)".*?$'),"$1")},invAttr:function(b,a){var c=[];for(var d in a)b.indexOf(a[d]+"=")>=0&&c.push(b.replace(RegExp("^.*?"+
a[d]+'="(.*?)".*?$'),"$1"));return c.length?"("+c.join(",")+")":""},style:function(b){b=b&&b.split(/,|;/);var a,c="";for(var d in b)if(b[d]!=null){a=b[d].split(":");c+=a[0]==">"?"margin-left:4em;":a[0]=="<"?"margin-right:4em;":a[0]==">>"?"float:right;":a[0]=="<<"?"float:left;":a[0]=="="?"display:block;margin:0 auto;":a[0]=="_"?"text-decoration:underline;":a[0]=="b"?"border:solid 1px;":a[0]=="c"?"color:"+a[1]+";":a[0]=="C"?"background:"+a[1]+";":a[0]=="w"?"width:"+a[1]+";":a[0]+":"+a[1]+";"}return c?
' style="'+c+'"':""},invStyle:function(b){b=(b=/style=/.test(b)?b.replace(/^.*?style=\"(.*?)\".*?$/,"$1"):"")&&b.split(";");var a,c=[];for(var d in b){a=b[d].split(":");if(a[0]=="margin-left"&&a[1]=="4em")c.push(">");else if(a[0]=="margin-right"&&a[1]=="4em")c.push("<");else if(a[0]=="float"&&a[1]=="right")c.push(">>");else if(a[0]=="float"&&a[1]=="left")c.push("<<");else if(a[0]=="margin"&&a[1]=="0 auto")c.push("=");else if(a[0]=="text-decoration"&&a[1]=="underline")c.push("_");else if(a[0]=="border"&&
a[1]=="solid 1px")c.push("b");else if(a[0]=="color")c.push("c:"+a[1]);else if(a[0]=="background")c.push("C:"+a[1]);else if(a[0]=="width")c.push("w:"+a[1]);else a[0]&&c.push(a[0]+":"+a[1])}return c.length?"{"+c.join(",")+"}":""},sectionRule:function(b,a,c,d){a={p_p:"<p>$1</p>",p_u:"<p>$1</p><ul$3>",p_o:"<p>$1</p><ol$3>",u_p:"<li$2>$1</li></ul>",u_c:"<li$2>$1</li></ul></td>",u_r:"<li$2>$1</li></ul></td></tr>",uu_p:"<li$2>$1</li></ul></li></ul>",uo_p:"<li$2>$1</li></ol></li></ul>",uuu_p:"<li$2>$1</li></ul></li></ul></li></ul>",
uou_p:"<li$2>$1</li></ul></li></ol></li></ul>",uuo_p:"<li$2>$1</li></ol></li></ul></li></ul>",uoo_p:"<li$2>$1</li></ol></li></ol></li></ul>",u_u:"<li$2>$1</li>",uu_u:"<li$2>$1</li></ul></li>",uo_u:"<li$2>$1</li></ol></li>",uuu_u:"<li$2>$1</li></ul></li></ul></li>",uou_u:"<li$2>$1</li></ul></li></ol></li>",uuo_u:"<li$2>$1</li></ol></li></ul></li>",uoo_u:"<li$2>$1</li></ol></li></ol></li>",u_uu:"<li$2>$1<ul$3>",u_o:"<li$2>$1</li></ul><ol$3>",uu_o:"<li$2>$1</li></ul></li></ul><ol$3>",uo_o:"<li$2>$1</li></ol></li></ul><ol$3>",
uuu_o:"<li$2>$1</li></ul></li></ul></li></ul><ol$3>",uou_o:"<li$2>$1</li></ul></li></ol></li></ul><ol$3>",uuo_o:"<li$2>$1</li></ol></li></ul></li></ul><ol$3>",uoo_o:"<li$2>$1</li></ol></li></ol></li></ul><ol$3>",u_uo:"<li$2>$1<ol$3>",o_p:"<li$2>$1</li></ol>",oo_p:"<li$2>$1</li></ol></li></ol>",ou_p:"<li$2>$1</li></ul></li></ol>",ooo_p:"<li$2>$1</li></ol></li></ol>",ouo_p:"<li$2>$1</li></ol></li></ul></li></ol>",oou_p:"<li$2>$1</li></ul></li></ol></li></ol>",ouu_p:"<li$2>$1</li></ul></li></ul></li></ol>",
o_u:"<li$2>$1</li></ol><ul$3>",oo_u:"<li$2>$1</li></ol></li></ol><ul$3>",ou_u:"<li$2>$1</li></ul></li></ol><ul$3>",ooo_u:"<li$2>$1</li></ol></li></ol></li></ol><ul$3>",ouo_u:"<li$2>$1</li></ol></li></ul></li></ol><ul$3>",oou_u:"<li$2>$1</li></ul></li></ol></li></ol><ul$3>",ouu_u:"<li$2>$1</li></ul></li></ul></li></ol><ul$3>",o_ou:"<li$2>$1<ul$3>",o_o:"<li$2>$1</li>",oo_o:"<li$2>$1</li></ol></li>",ou_o:"<li$2>$1</li></ul></li>",ooo_o:"<li$2>$1</li></ol></li></ol></li>",ouo_o:"<li$2>$1</li></ol></li></ul></li>",
oou_o:"<li$2>$1</li></ul></li></ol></li>",ouu_o:"<li$2>$1</li></ul></li></ul></li>",o_oo:"<li$2>$1<ol$3>",l_d:"<dt>$1</dt>",d_l:"<dd>$1</dd>",d_u:"<dd>$1</dd></dl><ul>",d_o:"<dd>$1</dd></dl><ol>",p_l:"<p>$1</p><dl>",u_l:"<li$2>$1</li></ul><dl>",o_l:"<li$2>$1</li></ol><dl>",uu_l:"<li$2>$1</li></ul></li></ul><dl>",uo_l:"<li$2>$1</li></ol></li></ul><dl>",ou_l:"<li$2>$1</li></ul></li></ol><dl>",oo_l:"<li$2>$1</li></ol></li></ol><dl>",d_p:"<dd>$1</dd></dl>",p_t:"<p>$1</p><table>",p_r:"<p>$1</p></td></tr>",
p_c:"<p>$1</p></td>",t_p:"</table><p>$1</p>",r_r:"<tr><td>$1</td></tr>",r_p:"<tr><td><p>$1</p>",r_c:"<tr><td>$1</td>",r_u:"<tr><td>$1<ul>",c_p:"<td><p>$1</p>",c_r:"<td>$1</td></tr>",c_c:"<td>$1</td>",u_t:"<li$2>$1</li></ul><table>",o_t:"<li$2>$1</li></ol><table>",d_t:"<dd>$1</dd></dl><table>",t_u:"</table><p>$1</p><ul>",t_o:"</table><p>$1</p><ol>",t_l:"</table><p>$1</p><dl>"};for(var e="",f="",g=Math.max(b.length,d.length),h=true,k={"0":"decimal-leading-zero","1":"decimal",a:"lower-alpha",A:"upper-alpha",
i:"lower-roman",I:"upper-roman",g:"lower-greek"}[d.charAt(d.length-1)],j=0;j<g;j++)if(b.charAt(j+1)!=d.charAt(j+1)||!h||j==g-1){e+=b.charAt(j)==undefined?" ":b.charAt(j);f+=d.charAt(j)==undefined?" ":d.charAt(j);h=false}d=(e+"_"+f).replace(/([01AIagi])/g,"o");return!a[d]?"?("+d+")":a[d].replace(/\$2/,' class="'+b+'"').replace(/\$3/,!k?"":' style="list-style-type:'+k+';"').replace(/\$1/,c).replace(/<p><\/p>/,"")},word:function(b){b=b.split("/");return b[b.length-1].replace(/([a-z])([A-Z])/g,"$1 $2")}};
